### ISSUE TITLE
Not worked with Hotfix #4

### ISSUE THREAD

**Issue by UnknownUserMeMe** [shalzuth/BG3Cam#11]

**Comment by Grammernatzi** [comment]
Currently working for Hotfix 4 here. Can you elaborate?

**Comment by cCaptainn** [comment]
I'm having the same issue. An error occurs stating "Max Zoom not found, expected 12.0, found  : 0" when I launch the exe.

**Comment by Grammernatzi** [comment]
Did you run it as administrator?

**Comment by UnknownUserMeMe** [comment]
There was two versions of Hotfix #4. BG3 cam was not worked with 1st version, but worked fine with second version :D
I always run BG3 cam under the administrator.
