### ISSUE TITLE
Camera keeps moving long after mouse has stopped moving

### ISSUE THREAD

**Issue by AlexRDX** [shalzuth/BG3Cam#4]
I checked the code, and I think this is because the diff variable has no bounds, so when you calculate the difference between mouse position, the time it takes for the camera to adjust might be too slow. You could try bounding the diff variable, by setting a max value it can get to. That way whenever you stop moving your mouse, the camera stops too.

**Comment by Ch4nKyy** [comment]
To be honest, I think it is enough to pick a small enough value for it.

I guess it would be possible to add logic that stops the rotation, when you release the mouse, but then it will get even more tedious to rotate. I kinda like the drag effect it has right now.

I think it would be more beneficial to find and edit the speed with which the camera updates its vertical rotation.

**Comment by AlexRDX** [comment]
> To be honest, I think it is enough to pick a small enough value for it.
> 
> I guess it would be possible to add logic that stops the rotation, when you release the mouse, but then it will get even more tedious to rotate. I kinda like the drag effect it has right now.
> 
> I think it would be more beneficial to find and edit the speed with which the camera updates its vertical rotation.

Yeah, true. Were you able to find anything related to the tilt speed?
I disabled the drag with this, but the camera is still slow
`        async Task ChangePitchOnMouseMove()
        {
            while (running)
            {
                if (Hotkeys.SinglePress(Keys.RButton)) prevMouseY = Cursor.Position.Y;
                if (Hotkeys.IsPressed(Keys.RButton))
                {
                    
                    var diff = Cursor.Position.Y - prevMouseY;
                    var diff_avg = Math.Abs(diff * 0.5f) + Math.Abs(prevDiff * 0.5f);
                    var dmax = 0.6f;
                    if (diff_avg >= 5)
                    {
                        curTilt += Math.Max(-dmax, Math.Min(dmax, diff));
                        mem.WriteProcessMemory(obj + worldCamOffset + camTiltOffset, curTilt);
                        mem.WriteProcessMemory(obj + worldCamOffset + camTiltOffset + 4, curTilt);
                        mem.WriteProcessMemory(obj + worldCamOffset + camTiltOffset + 8, curTilt);
                        mem.WriteProcessMemory(obj + worldCamOffset + camTiltOffset + 12, curTilt);
                        mem.WriteProcessMemory(obj + battleCamOffset + camTiltOffset, curTilt);
                        mem.WriteProcessMemory(obj + battleCamOffset + camTiltOffset + 4, curTilt);
                        mem.WriteProcessMemory(obj + battleCamOffset + camTiltOffset + 8, curTilt);
                        mem.WriteProcessMemory(obj + battleCamOffset + camTiltOffset + 12, curTilt);
                        prevMouseY = Cursor.Position.Y;
                        prevDiff = diff;
                    }
                }
                await Task.Delay(8);
            }
        }`

**Comment by shalzuth** [comment]
pan speed fixes this
