### ISSUE TITLE
Controller qol

### ISSUE THREAD

**Issue by hidden12323** [shalzuth/BG3Cam#6]
Would it be possible to make the right stick control the tilt without pressing it so it feels like a third person game?
Another great feature would be to revert the panning when a battle starts because its impossible to aim.

**Comment by ssltg** [comment]
This would only be possible if I interrupt the native controls. Technically possible, but not that easy as the current solution. I'll take a look, but no promises made.

**Comment by shalzuth** [comment]
sslth added this

**Comment by BramHoep** [comment]
How do you enable it? It doesnt work like this by default.
