### ISSUE TITLE
Nexus version is outdated

### ISSUE THREAD

**Issue by Ferunelli** [shalzuth/BG3Cam#7]
There is a new PR merged for controller support, it is very useful and I really want it. But nexus version is outdated and currently I don't have a possibility to build it manually. Can you build and upload the newest version please

**Comment by Ferunelli** [comment]
Or at least, can you please write a brief description of how to build and run the project for those who are not used to c#

**Comment by ssltg** [comment]
Published a pre-release version for those who cannot wait: https://github.com/ssltg/BG3Cam/releases

**Comment by v1ld** [comment]
Not seeing the pre-release version in your repo's releases, @ssltg.  Can you please re-publish?

Would love to have this on the Steam Deck.

**Comment by ssltg** [comment]
Sorry messed up with the files: https://github.com/ssltg/BG3Cam/releases/tag/unpublished
It is much bigger than the original, I guess because it packed all the controller Stuff in there.
Would love to know if this works on Steam Deck, Doesn't have one to try it out.

**Comment by ssltg** [comment]
Yeah, i am not quite sure why. But to be honest i never build with visual studio before (at least in the last 20 years :D ). The version I build first was smaller, but it didn't run from another folder (without the dlls vs also put there), so i rebuild it as a "standalone version".  I hope @shalzuth can build it smaller.
Out of curiosity: What size is your exe, and does it run outside of the build directory?

**Comment by Grammernatzi** [comment]
It runs out of the directory, I just have to bring the dlls with it. But
combined with the dlls it's nowhere near that size, which is quite odd.

**Comment by ssltg** [comment]
I build a new one with the setting "Framework-dependent" I guess this one needs the .net7 runtimes: https://github.com/ssltg/BG3Cam/releases/tag/unpublished-framework

**Comment by shalzuth** [comment]
github actions builds to https://github.com/shalzuth/BG3Cam/releases/tag/alpha now
